
export const ratingList:Irating[] = [
    {key: 1, nomer: 1, name: 'Дамирсынба', photo: '/damirsinba.png', points: 12},
    {key: 2, nomer: 2, name: 'РПГ', photo: '/rpg.png', points: 10},
    {key: 3, nomer: 3, name: 'Димон', photo: '/dimon.jpg', points: 10},
    {key: 4, nomer: 4, name: 'Исмолингс', photo: '/ismolings.png', points: 8},
    {key: 5, nomer: 5, name: 'Родик', photo: '/rodik.jpeg', points: 7},
    {key: 6, nomer: 6, name: 'Рауф', photo: '/rauf.png', points: 6},
    {key: 7, nomer: 7, name: 'Шизик', photo: '/shizik.png', points: 5},
    {key: 8, nomer: 8, name: 'Саня', photo: '/sanya.jpg', points: 4},
    {key: 9, nomer: 9, name: 'Стул', photo: '/stul.png', points: 4},
    {key: 10, nomer: 10, name: '8 и 7 части', photo: '/placeholder-image.png', points: 4},
    {key: 11, nomer: 11, name: 'Руслан', photo: '/ruslan.png', points: 3},
    {key: 12, nomer: 12, name: 'Рауан', photo: '/rauan.jpeg', points: 3},
    {key: 13, nomer: 13, name: 'Мудрец', photo: '/mudrec.jpg', points: 3},
    {key: 14, nomer: 14, name: 'Ютуб', photo: '/placeholder-image.png', points: 3},
    {key: 15, nomer: 15, name: 'Терминатор Дамир', photo: '/damirterminator.png', points: 1},
    {key: 16, nomer: 16, name: 'Терминатор', photo: '/terminator.png', points: 1},
    {key: 17, nomer: 17, name: 'Челик в капюшоне', photo: '/chel.jfif', points: 1},
    {key: 18, nomer: 18, name: 'Мадияр', photo: '/madiyar.png', points: 0},
    {key: 19, nomer: 19, name: 'Роналдо', photo: '/ronaldo.jpg', points: 0},
    {key: 20, nomer: 20, name: 'Питлер', photo: '/placeholder-image.png', points: 0},
]